import {StyleSheet, Text, View} from 'react-native';
import React from 'react';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';

export const globalstyles = StyleSheet.create({
  maincont: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  logocont: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: responsiveWidth(10),
    marginBottom: responsiveHeight(3),
  },
  logocont2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: responsiveWidth(10),
    marginBottom: responsiveHeight(1),
  },
  logotext: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#3b74f7',
  },
  logo: {
    height: 80,
    width: 100,
    resizeMode: 'contain',
  },
  btncont: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    width: '100%',
    paddingTop: 10,
  },
  btncont2: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    width: '100%',
    paddingTop: 2,
  },
  activebtn: {
    height: 40,
    width: 120,
    backgroundColor: '#3b74f7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  inactivebtn: {
    height: 40,
    width: 120,
    backgroundColor: '#b3d7ff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  text: {
    fontSize: 20,
    color: 'black',
  },
  input: {
    width: responsiveWidth(70),
    borderColor: 'grey',
    borderWidth: 1,
    paddingHorizontal: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginVertical: 10,
  },
  input2: {
    width: responsiveWidth(70),
    borderColor: 'grey',
    borderWidth: 1,
    paddingHorizontal: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginVertical: 10,
    height: 40,
  },
  picker: {
    width: responsiveWidth(70),
    borderColor: 'grey',
    borderWidth: 1,
    paddingHorizontal: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginVertical: 10,
    height: 40,
    color: 'grey',
  },
  inputcont: {
    marginTop: 10,
  },
  forgottext: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#94b2f7',
    marginLeft: responsiveWidth(41),
  },
  btn: {
    backgroundColor: '#94b2f7',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    width: responsiveWidth(70),
    borderRadius: 10,
  },
  btn2: {
    backgroundColor: '#94b2f7',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
    width: responsiveWidth(70),
    borderRadius: 10,
  },
  btntext: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  noaccounttext: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#94b2f7',
    marginTop: 20,
  },
  signuptext: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#3b74f7',
  },
  headercont: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
    paddingBottom: 4,
    // marginTop: 10,
    borderBottomColor: '#94b2f7',
    borderBottomWidth: 1,
    marginBottom: 10,
    backgroundColor: '#d9e3fa',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    height: 70,
  },
  headertext: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3b74f7',
  },
  user: {
    height: 30,
    width: 30,
    borderRadius: 50,
    resizeMode: 'contain',
  },
  bell: {
    height: 30,
    width: 30,
    borderRadius: 50,
    resizeMode: 'contain',
    marginRight: 10,
  },
  uploadcont: {
    margin: 10,
  },
  uploadtext: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
    marginLeft: responsiveWidth(3),
  },
  servicescont: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: responsiveWidth(100),
    paddingHorizontal: 20,
    paddingBottom: 4,
    marginTop: 15,
    marginBottom: 15,
  },
  servicescard4: {
    height: 70,
    width: responsiveWidth(20),
    backgroundColor: '#c0e9fc',

    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  servicescard1: {
    height: 70,
    width: responsiveWidth(20),
    backgroundColor: '#fa927d',

    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  servicescard2: {
    height: 70,
    width: responsiveWidth(20),
    backgroundColor: '#bfc4c7',

    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  servicescard3: {
    height: 70,
    width: responsiveWidth(20),
    backgroundColor: '#fcd4cc',

    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  servicestext: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
    marginLeft: responsiveWidth(3),
  },
  textcont: {
    width: responsiveWidth(50),
    justifyContent: 'center',
    alignItems: 'center',
  },
  smalltext: {
    fontSize: 13,
    // fontWeight: 'bold',
    color: 'black',
    marginLeft: responsiveWidth(3),
  },
  minicont: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: responsiveWidth(90),
    paddingHorizontal: 20,
    paddingBottom: 4,
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: '#c0e9fc',
    alignSelf: 'center',
    marginBottom: 10,
  },
  doctor: {
    height: 180,
    width: 180,
    resizeMode: 'contain',
  },
  appointmentcard: {
    height: 100,
    width: responsiveWidth(60),
    backgroundColor: '#94b2f7',
    borderRadius: 10,
    justifyContent: 'space-around',
    alignItems: 'center',
    marginHorizontal: 10,
    flexDirection: 'row',
  },
  appointmenttextb: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  appointmenttext: {
    fontSize: 15,
    // fontWeight: 'bold',
    color: 'black',
  },
  appointmentcont2: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#b9cdfa',
    padding: 10,
    borderRadius: 10,
  },
  appointmentcont: {
    marginTop: 15,
  },
  doctorcont1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: responsiveWidth(90),
    paddingBottom: 4,
    marginTop: 10,
    borderRadius: 10,
    alignSelf: 'center',
    // backgroundColor: '#c0e9',
  },
  doctorcont2: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#c0e9fc',
    padding: 10,
    borderRadius: 10,
    width: responsiveWidth(40),
    marginHorizontal: 10,
  },
  doctorimg: {
    height: 100,
    width: 100,
    resizeMode: 'contain',
    borderRadius: 50,
  },
  dotorbtn: {
    backgroundColor: '#94b2f7',
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 10,
    borderRadius: 10,
  },
  notificationcont: {
    flexDirection: 'row',
    alignItems: 'center',
    width: responsiveWidth(80),
    paddingBottom: 4,
    marginTop: 10,
    borderRadius: 10,
    alignSelf: 'center',
    backgroundColor: '#c0e9fc',
    paddingHorizontal: 10,
  },
  notificationtext: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'black',
    // marginLeft: responsiveWidth(3),
  },
  settingcont: {
    backgroundColor: '#94b2f7',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 20,
    borderRadius: 10,
    width: responsiveWidth(70),
  },
  modal: {
    backgroundColor: '#fff',
    padding: 18,
    borderRadius: 15,
  },
  modaltextmain: {
    color: '#565656',
    fontSize: 20,
    textAlign: 'center',
    borderBottomColor: '#E4E4E4',
    borderBottomWidth: 2,
    fontWeight: '700',
  },
  modaltextcont: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: responsiveHeight(2),
  },
  modalbtn: {
    marginTop: responsiveHeight(2),
    alignSelf: 'center',
    backgroundColor: '#c8dffa',
    height: 30,
    width: 70,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  modalgreentext: {
    color: '#0F7B32',
    fontSize: 15,
    fontWeight: '600',
  },
  modalredtext: {
    color: 'red',
    fontSize: 15,
    fontWeight: '600',
  },
  patientcont: {
    // backgroundColor: '#94b2f7',
    padding: 10,
    marginVertical: 10,
  },
  patientcard: {
    width: responsiveWidth(30),
    backgroundColor: '#fcb3a4',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 10,
  },
  inputcont2: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: responsiveWidth(90),
    paddingBottom: 4,
    marginTop: 10,
    borderRadius: 10,
    alignSelf: 'center',
    // backgroundColor: '#c0e9fc',
  },
  input3: {
    width: responsiveWidth(40),
    borderColor: 'grey',
    borderWidth: 1,
    paddingHorizontal: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginVertical: 10,
  },
  doctorcard: {
    width: responsiveWidth(35),
    backgroundColor: '#c0e9fc',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 10,
  },
  rdbtn: {
    backgroundColor: '#c45652',
    // height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginRight: 5,
    borderRadius: 8,
    // width: responsiveWidth(15),
  },
  greenbtn: {
    backgroundColor: '#4e824e',
    // height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginRight: 5,
    borderRadius: 8,
    // width: responsiveWidth(15),
  },
});
